[project]
name = "NetcdfMicroservice"
requires-python = ">=3.7"
version = "0.3.1"
description = "A microservice for netcdf files"

[project.optional-dependencies]
dev = [ "black", "sphinx", "coverage[toml]", "myst-nb", "sphinx-autoapi", "sphinx_rtd_theme",]

[tool.black]
addopts = "-v"
